### ISSUE TITLE
Not able to create new queue

### ISSUE THREAD

**Issue by siddharth-sable** [kaptinlin/queue#1]
Hello @kaptinlin, I was trying to enqueue my msgs into different queue other than default queue. But the function queue.WithQueue() is not able to override the deafult queue. 

Below is the sample code:
```go
func SendTelegramMessageToQueue(payload models.QueueTask) error {
	job := queue.NewJob(telegramJobType, payload, queue.WithQueue("telegram"))
	_, err := client.EnqueueJob(job)
	if err != nil {
		log.Printf("Failed to enqueue job: %v", err)
	}
	return nil
}
``` 
The above code enqueues in default queue, in spite of using telegram as the queue.

Also can you provide some insights on how the workers will work to dequeue the msgs, when not in default queue.
Everything works great when in default queue. For my use case I need to create multiple queues. Any help would be highly appreciated.

**Comment by kaptinlin** [comment]
I've also noticed this issue, and I will fix it today. Thank you for reporting the bug.

**Comment by kaptinlin** [comment]
Fixed and updated docs and examples! Check out the [Priority Queues Docs](https://github.com/kaptinlin/queue/blob/main/docs/priorities.md) and the [Custom Queue Example](https://github.com/kaptinlin/queue/blob/main/examples/simple/cmd/worker/main.go).

**Comment by siddharth-sable** [comment]
Thank you, much appreciated
